#!/usr/bin/env bash

if [ ! -d "$HOME/.virtualenv" ]; then
  mkdir "$HOME/.virtualenv"
fi
if [ ! -d "$HOME/.virtualenv/base" ]; then
  python3 -m venv "$HOME/.virtualenv/base"
fi

if [ ! -d "$HOME/.virtualenv/$1" ]; then
  python3 -m venv "$HOME/.virtualenv/$1"
elif [ ! $1 ]; then
  echo "Enter virtualenv name."
else
  echo "Virtual environment already exists."
fi
